//xenowear for the loadout tab
#define LOADOUT_CATEGORY_XENOWEAR 				"Xenowear"
#define LOADOUT_SUBCATEGORY_XENOWEAR_TESHARI	"Teshari"
#define LOADOUT_SUBCATEGORY_XENOWEAR_CLOAK_S	"Standard"
#define LOADOUT_SUBCATEGORY_XENOWEAR_CLOAK_H	"Hooded"
#define LOADOUT_SUBCATEGORY_XENOWEAR_CLOAK_B	"Beltcloak"